FROM node:alpine as BUILD
WORKDIR /home/app
COPY ./src ./src
COPY ./package.json ./package.json
COPY ./webpack.config.js ./webpack.config.js
RUN npm install
RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=BUILD /home/app/bundle /usr/share/nginx/html
