sudo: required
services:
  - docker

before-install:
  - docker build -t fpezzati/routedrawingbook -f ./routedrawingbook/Dockerfile.dev .

scripts:
  - docker run -v $(pwd):/home/app fpezzati/routedrawingbook npm run test
